### ISSUE TITLE
Potential typing mistake?

### ISSUE THREAD

**Issue by ghost** [Mrhudson69/Mailcow-Setup-inside-LXC-Proxmox#1]
`apt-get install cgroups-mount`

should that be `apt-get install cgroupfs-mount`?

**Comment by Mrhudson69** [comment]
`apt-get install cgroups-mount` is correct not a mistake because need to load overlay and naufs module on proxmox host.

**cgroups-mount:** This package is typically used in systems where you need to mount cgroups using systemd (or its utilities), and it's a bit less common.

**cgroupfs-mount:** This is the more common package that is used to mount the cgroup filesystem in systems where cgroup management is handled by cgroupfs, a userspace tool for cgroups. This package is more frequently seen in distributions using docker, kubernetes, or other containerization tools that directly manipulate cgroup filesystems.
